version: "3"
services:
  snappy-app:
    build: public/
    ports:
      - "80:3000"
    networks:
      - snappy-network
  snappy-api:
    build: server/
    ports:
      - "5000:5000"
    networks:
      - snappy-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - snappy-network

networks:
  snappy-network: 
    driver: bridge
